### PR TITLE
fix: using --directory to set protoc output path (Issue  #177)

### PR DESCRIPTION
**Pull request by markdoerr**
Here is a suggestion to fix the protoc _pb2 generation output path, using the --directory option.

This would solve #177 .

### CODE REVIEW

**Comment by markdoerr** [comment]
Thanks, @legau, for your comment,
I agree - if I understood your comment correctly - and make a suggestion to solve it.

**Comment by markdoerr** [comment]
@legau , 
I added the proto_path option.
Still need to test everything.

**Comment by AMontagu** [comment]
Hello @markdoerr 

Can we close this PR ?

**Comment by markdoerr** [comment]
@AMontagu, 
yes, I think, we can close it until we managed to finialise the examples ... sorry for all the delays :(

**Pull request closed without merging**
